# Naive Bayes - Titanic

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [10]:
url = "https://raw.githubusercontent.com/nicoavilan/Bases-de-datos/main/titanic.csv"
df = pd.read_csv(url)
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [47]:
target = df.Survived

In [11]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [12]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [30]:
X = df[["Pclass", "Sex" ,"Age", "Fare"]]
X

Pclass     Sex   Age     Fare
0         3    male  22.0   7.2500
1         1  female  38.0  71.2833
2         3  female  26.0   7.9250
3         1  female  35.0  53.1000
4         3    male  35.0   8.0500
..      ...     ...   ...      ...
886       2    male  27.0  13.0000
887       1  female  19.0  30.0000
888       3  female   NaN  23.4500
889       1    male  26.0  30.0000
890       3    male  32.0   7.7500

[891 rows x 4 columns]

In [31]:
pd.get_dummies(X.Sex)

female  male
0         0     1
1         1     0
2         1     0
3         1     0
4         0     1
..      ...   ...
886       0     1
887       1     0
888       1     0
889       0     1
890       0     1

[891 rows x 2 columns]

In [32]:
# dummies = pd.get_dummies(X.Sex, drop_first=True)
dummies = pd.get_dummies(X.Sex)
dummies

female  male
0         0     1
1         1     0
2         1     0
3         1     0
4         0     1
..      ...   ...
886       0     1
887       1     0
888       1     0
889       0     1
890       0     1

[891 rows x 2 columns]

In [33]:
X = pd.concat([X, dummies.female], axis=1)
X

Pclass     Sex   Age     Fare  female
0         3    male  22.0   7.2500       0
1         1  female  38.0  71.2833       1
2         3  female  26.0   7.9250       1
3         1  female  35.0  53.1000       1
4         3    male  35.0   8.0500       0
..      ...     ...   ...      ...     ...
886       2    male  27.0  13.0000       0
887       1  female  19.0  30.0000       1
888       3  female   NaN  23.4500       1
889       1    male  26.0  30.0000       0
890       3    male  32.0   7.7500       0

[891 rows x 5 columns]

In [34]:
X.drop("Sex", axis=1, inplace=True)

In [35]:
X.head()

Pclass   Age     Fare  female
0       3  22.0   7.2500       0
1       1  38.0  71.2833       1
2       3  26.0   7.9250       1
3       1  35.0  53.1000       1
4       3  35.0   8.0500       0

In [36]:
X.isnull().sum()

Pclass      0
Age       177
Fare        0
female      0
dtype: int64

In [37]:
X.isna().any()

Pclass    False
Age        True
Fare      False
female    False
dtype: bool

In [38]:
X.columns[X.isna().any()]

Index(['Age'], dtype='object')

In [40]:
X.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

## Imputación de los datos

In [41]:
X.Age.mean()

29.69911764705882

In [42]:
X.Age.median()

28.0

In [44]:
X.Age.fillna(X.Age.median(), inplace=True)

In [45]:
X.head(10)

Pclass   Age     Fare  female
0       3  22.0   7.2500       0
1       1  38.0  71.2833       1
2       3  26.0   7.9250       1
3       1  35.0  53.1000       1
4       3  35.0   8.0500       0
5       3  28.0   8.4583       0
6       1  54.0  51.8625       0
7       3   2.0  21.0750       0
8       3  27.0  11.1333       1
9       2  14.0  30.0708       1

In [46]:
X.isnull().sum()

Pclass    0
Age       0
Fare      0
female    0
dtype: int64

In [48]:
X_train , X_test , y_train , y_test = train_test_split(X, target, test_size=0.25, random_state=23)

In [49]:
len(X_train)

668

In [50]:
len(X_test)

223

In [51]:
len(X)

891

In [53]:
from sklearn.naive_bayes import GaussianNB

In [54]:
model = GaussianNB()

In [55]:
model.fit(X_train, y_train)

GaussianNB()

In [56]:
model.score(X_test, y_test)

0.8116591928251121

In [57]:
model.predict(X_train)

array([0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,

In [58]:
model.score(X_test, y_test)

0.8116591928251121

In [59]:
np.mean(y_train == model.predict(X_train))

0.7664670658682635

In [61]:
np.mean(y_test == model.predict(X_test))

0.8116591928251121

In [62]:
X.head()

Pclass   Age     Fare  female
0       3  22.0   7.2500       0
1       1  38.0  71.2833       1
2       3  26.0   7.9250       1
3       1  35.0  53.1000       1
4       3  35.0   8.0500       0

In [64]:
model.predict([[2, 25, 15, 1]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


array([1])

In [65]:
model.predict(X_test[:10])

array([1, 0, 0, 1, 0, 0, 0, 0, 1, 0])

In [67]:
model.predict_proba(X_test[:10])  # Predicción de las probabilidades

array([[0.41067068, 0.58932932],
       [0.96224426, 0.03775574],
       [0.95448267, 0.04551733],
       [0.36640896, 0.63359104],
       [0.89344859, 0.10655141],
       [0.95748664, 0.04251336],
       [0.92231111, 0.07768889],
       [0.95217775, 0.04782225],
       [0.40030274, 0.59969726],
       [0.96078151, 0.03921849]])